# I used IA to help me to creat one part of the story...
print("It’s your first day as the newly elected president. A national broadcast has been scheduled so the entire country can hear your very first decision in office. You sit at the desk, the cameras begin recording, and millions of people wait to know what you will announce.")
print()
print("You have two proposals prepared. The first encourages daily spiritual study. The second promotes learning through missionary messages.")
print()
print("Do you announce:")
print()
print("1: A tax reduction for all citizens who read one chapter of the Book of Mormon every day?")
print()
print("2: A national open broadcast of the missionaries’ messages, where citizens who watch and correctly answer questions about the teachings will pay only 10% taxes forever?")
print()
first_choise = input("(BOOK/MESSAGES): ")
first_choise = first_choise.upper()
print()
if first_choise == "BOOK":
    print("  After announcing the tax reduction for everyone who reads one chapter of the Book of Mormon per day, something surprising happens: people don’t just read one chapter… they keep reading. And reading. And reading.")
    print("  Across the country, bookshops run out of copies, online downloads break records, and social media is filled with discussions, quotes, and questions.")
    print()
    print("  Soon, thousands begin sending messages to the government asking for guidance, explanations, and help understanding certain passages. The nation is hungry for answers, and everyone waits for your next public statement.")
    print()
    print("  Do you declare:")
    print()
    print(" 1) A weekly national Q&A broadcast where missionaries and church leaders answer the people's most questions?")
    print(" 2) A government program offering free study groups in every city, where trained volunteers help anyone learn and understand the teachings?")
    print()
    second_choise = input("(BROADCAST/GROUPS): ")
    second_choise = second_choise.upper()
    print()
    if second_choise == "BRODCAST":
        print("  Your announcement of a weekly national Q&A broadcast immediately brings calm to the nation.")
        print("  Every Sunday evening, millions of people tune in to watch scholars, missionaries, and leaders answer questions live. Families gather, friends meet, and the whole country seems united by one purpose: aproch to Christ.")
        print("  However, the audience keeps growing so fast that the broadcast team is struggling to keep up. You must decide how to expand the program.")
        print()
        print("Do you:")
        print()
        print(" 1) Create a 24-hour online platform where people can submit questions anytime?")
        print(" 2) Bild more chapers to support every one with questions?")
        print()
        third_choise = input("(PLATAFORM/BILD)")
        third_choise = third_choise.upper()
        print()
        if third_choise == "PALATAFORM":
            print("  The 24-hour platform becomes the most active spiritual website in the nation.")
            print("  People send thousands of questions every hour. Volunteers and missionaries work day and night to respond with kindness and clarity.")
            print()
            print(" Many citizens begin requesting baptism after receiving personal answers.")
            print()
            print("ENDING:  Missionaries meet with families in their homes, preparing each person with care. The nation slowly transforms into a place of unity and faith. The Church becomes widely known and respected throughout the country.")
        elif third_choise == "BILD":
            print("  Service, unity, and faith grow so much that the nation begins to live 'with one heart and one mind.'")
            print("  ENDING: Eventually, the entire country becomes so righteous that, like the city of Enoch, it is lifted and translated together into the presence of God.")
    elif second_choise == "GROUPS":
        print(" The free study groups explode in popularity.")
        print("  Community centers fill up. Volunteers teach every day, and strangers become friends while studying side by side. The country feels more peaceful, more connected, and more curious than ever before.")
        print("  But soon, the demand becomes overwhelming—some groups have waiting lists of hundreds.")
        print()
        print("Do you:")
        print()
        print(" 1) Launch a nationwide volunteer training program to increase the number of gospel principles teachers?")
        print(" 2) Create an official online study portal so people can learn from home without needing space in the groups?")
        print()
        third_choise = input("(TEACHERS/PORTAL): ")
        third_choise = third_choise.upper()
        print()
        if third_choise == "TEACHERS":
            print("  Thousands join the volunteer program, learning how to teach, serve, and explain the scriptures.")
            print("  Study groups multiply in every neighborhood, and spiritual friendships grow stronger than ever. As the nation becomes more unified, a new idea is proposed.")
            print()
            print("Do you: ")
            print()
            print(" 1) Create regional spiritual festivals to celebrate learning?")
            print(" 2) Encourage each city to create daily “moments of peace” dedicated to scripture reflection?")
            print()
            forth_choise = input("(CELEBRATING/REFLECTION): ")
            forth_choise = forth_choise.upper()
            print()
            if forth_choise == "CELEBRATING":
                print("ENDING: Festivals bring families together for music, service projects, study, and testimony.Many feel inspired to be baptized, and the Church grows rapidly nationwide.")
            elif forth_choise == "REFLECTION":
                print("ENDING: The daily reflection strengthens homes and communities.Over time, the entire nation becomes known for its kindness and faith.Your country becomes a global example of Christlike living.")
            else:
                print("SORRY, I didn't undestand your answer and I don't know while to remake the question yet... Restart the game.")
        elif third_choise == "PORTAL":
            print("The portal becomes the most visited website in the nation. People study on their phones, on buses, during lunch breaks, and even late at night. The teachings reach more hearts than ever before.")
            print()
            print("Then a surprising movement begins: Entire cities start requesting official spiritual events.")
            print()
            print("Do you: ")
            print()
            print(" 1) Approve public scripture-reading gatherings in parks and plazas?")
            print(" 2) Approve a national “Day of Light,” dedicated to Christlike service and study?")
            print()
            forth_choise = input("(SCRIPTURE/SERVICE): ")
            forth_choise = forth_choise.upper()
            print()
            if forth_choise == "SCRIPTURE":
                print("ENDING: Cities are filled with peaceful reading circles and group discussions.Many choose baptism, and the Church becomes widely known for its message of hope.")
            elif forth_choise == "SERVICE":
                print("ENDING: The nation unites in service, love, and study.The spiritual harmony becomes so great that one day, the entire country is lifted translated like the people of Enoch becoming a holy place prepared for God.")
            else:
                print("SORRY, I didn't undestand your answer and I don't know while to remake the question yet... Restart the game.")
        else:
            print("SORRY, I didn't undestand your answer and I don't know while to remake the question yet... Restart the game.")
    else:
        print("SORRY, I didn't undestand your answer and I don't know while to remake the question yet... Restart the game.")
elif first_choise == "MESSAGES":
    print("  Across the country, televisions switch to the live stream. Missionaries teach with clarity, warmth, and sincerity. People listen out of curiosity at first… but soon, they begin to enjoy the lessons. Families gather after dinner to watch. Students discuss the teachings in school.Even those who never thought about religion feel something newsomething peaceful.")
    print("  Within days, the broadcast becomes the number one program nationwide.")
    print()
    print("  Then something surprising happens: Millions of people start sending messages to the government asking how to learn more, how to study deeper, and how to talk with missionaries personally. The nation is hungry for answers.")
    print()
    print("  Do you declare:")
    print()
    print(" 1) Launch a national live Q&A program with missionaries every evening?")
    print(" 2) Approve local “Missionary Learning Centers” where people can study and talk in person?")
    print()
    second_choise = input("(LIVE/PERSON): ")
    second_choise = second_choise.upper()
    print()
    if second_choise == "LIVE":
        print("  The evening Q&A becomes a new national habit. Every night, people sit with family or friends to watch missionaries answer questions live.Phones, TVs, and laptops light up across the country. Questions flood in—thousands every hour.")
        print("  But soon, it becomes clear: People don’t want just to watch. They want to participate directly.")
        print()
        print("Do you:")
        print()
        print(" 1) Create interactive online groups where people meet missionaries through video calls?")
        print(" 2) Organize large monthly national missionary events in stadiums and public squares?")
        print()
        third_choise = input("(ONLINE/EVENTS): ")
        third_choise = third_choise.upper()
        print()
        if third_choise == "ONLINE":
            print("  The online groups explode in popularity.People can finally talk face-to-face with missionaries, ask honest questions, learn at their own pace, and feel supported.")
            print("  Within weeks, tens of thousands request baptism.Not long after, the number reaches millions.")
            print()
            print(" Many citizens begin requesting baptism after receiving personal answers.")
            print()
            print("ENDING:  Your presidency becomes known as'The Presidency of Light.'")
        elif third_choise == "EVENTS":
            print("  The monthly missionary events become legendary. Stadiums fill with families, friends, and entire communities eager to hear messages of peace, hope, and Christlike love.News stations report overwhelmingly positive reactions.The Church earns deep respect from the whole country.")
            print("  ENDING: Within a few months, almost everyone knows the teachings, and many choose to follow them and be baptized.")
        else:
            print("SORRY, I didn't undestand your answer and I don't know while to remake the question yet... Restart the game.")
    elif second_choise == "PERSON":
        print(" Missionary Learning Centers open in cities across the country.People stop by after work, during breaks, or on weekends.Missionaries welcome them warmly, offer study materials, answer questions, and build real friendships.")
        print("  Very quickly, the centers become packed. Lines form outside the doors.People want more time, more missionaries, more learning.")
        print()
        print("Do you:")
        print()
        print(" 1) Approve large regional conferences led by missionaries and local leaders?")
        print(" 2) Allow all centers to stay open 24 hours a day to handle the demand?")
        print()
        third_choise = input("(CONFERENCES/CENTERS): ")
        third_choise = third_choise.upper()
        print()
        if third_choise == "CONFERENCES":
            print("  The regional conferences bring huge groups of people together.Entire regions gather to study, learn, and strengthen their faith.The atmosphere is powerful full of unity and excitement.")
            print("ENDING:  Even the media reports that the country is going through a “national spiritual transformation.”Within a year, the majority of the population understands the teachings deeply, and millions decide to be baptized.Your leadership is remembered as truly inspired.")
        elif third_choise == "CENTERS":
            print("Once the centers stay open day and night, everything changes. People visit at sunrise, at midnight, on hard days, on happy days—whenever they feel the need. Communities grow more peaceful, supportive, and full of charity. Neighborhoods transform. Families unite. The whole nation moves toward harmony.")
            print()
            print("And then something miraculous happens: One quiet morning, a radiant light fills the sky. The entire nation is lifted translated, just like the ancient city of Enoch.")
            print()
            print("ENDING:  Your first presidential decision prepared the whole country for this divine destiny.")
        else:
            print("SORRY, I didn't undestand your answer and I don't know while to remake the question yet... Restart the game.")
    else:
        print("SORRY, I didn't undestand your answer and I don't know while to remake the question yet... Restart the game.")
else:
    print("SORRY, I didn't undestand your answer and I don't know while to remake the question yet... Restart the game.")